#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

if [ ! -f "problems/$1.input.txt" ]; then
    echo "The file problems/$1.input.py is not exist yet.";

    touch "problems/$1.py"
    echo "# https://www.acmicpc.net/problem/$1" > "problems/$1.py"
    code "problems/$1.py"
    google-chrome "https://www.acmicpc.net/problem/$1"

    node load.js "$1"
else
    if [ -f "problems/$1.your.txt" ]; then
        rm "problems/$1.your.txt";
    fi

    touch "problems/$1.your.txt"
    python3 "problems/$1.py" < "problems/$1.input.txt" > "problems/$1.your.txt"
    if [[ $(git diff --no-index "problems/$1.output.txt" "problems/$1.your.txt") ]]; then
        git diff --no-index "problems/$1.output.txt" "problems/$1.your.txt";
    else
        echo 'Your answer is good for in/output samples';
    fi
fi

