#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

case $1 in
  pibonacci|피보나치|pibonacci1|피보나치1)
    NUMBER=10870
    ;;
  pibonacci2|피보나치2)
    NUMBER=2747
    ;;
  pibonacci3|피보나치3)
    NUMBER=2748
    ;;
  pibonacci4|피보나치4)
    NUMBER=10826
    ;;
  pibonacci5|피보나치5)
    NUMBER=2749
    ;;
  *)
    NUMBER=$1
esac

code -a problems/${NUMBER}.py
